### ISSUE TITLE
api documenation is old

### ISSUE THREAD

**Issue by arahayrabedian** [datawrapper/datawrapper#156]
Hi guys, poor API documentation in the wiki has just set me back a couple of hours in my development of a python wrapper for the datawrapper API, in particular (and I'm just getting started):

``` javascript
{
    "email": "…",
    "pwhash": "…", // SHA256 hash of the password
    "time": "" // unix timestamp used for hashing the password
}
```

1) time is not required and the comment is misleading
2) `"keeplogin": true` is required at the current moment on master (as omitting it causes a 500, another bug i suppose) - this is NOT the case on datawrapper.de

I guess i'll update this issue with other things as I find as I find them.

**Comment by gka** [comment]
yep, we're working on a new version of the API docs that will be published on https://developers.datawrapper.de, hopefully later this year.
