### ISSUE TITLE
Getting This Error at visualizing step during chart creation

### ISSUE THREAD

**Issue by sadiq7753** [datawrapper/datawrapper#161]
Slim Application Error
The application could not run because of the following error:

Details

Code: 2
Message: file_get_contents(../wwwdefault.js): failed to open stream: No such file or directory
File: C:\MAMP\htdocs\datawrapper\lib\utils\chart_content.php
Line: 218
Trace
#0 [internal function]: Slim::handleErrors(2, 'file_get_conten...', 'C:\MAMP\htdocs\...', 218, Array)
#1 C:\MAMP\htdocs\datawrapper\lib\utils\chart_content.php(218): file_get_contents('../wwwdefault.j...')
#2 C:\MAMP\htdocs\datawrapper\lib\utils\chart_content.php(105): get_theme_js(false, Array)
#3 C:\MAMP\htdocs\datawrapper\controller\chart\preview.php(13): get_chart_content(Object(Chart), Object(User), NULL, NULL)
#4 [internal function]: {closure}(Object(User), Object(Chart))
#5 C:\MAMP\htdocs\datawrapper\lib\utils\check_chart.php(8): call_user_func(Object(Closure), Object(User), Object(Chart))
#6 C:\MAMP\htdocs\datawrapper\controller\chart\preview.php(18): check_chart_readable('lryAy', Object(Closure))
#7 [internal function]: {closure}('lryAy')
#8 C:\MAMP\htdocs\datawrapper\vendor\Slim\Route.php(395): call_user_func_array(Object(Closure), Array)
#9 C:\MAMP\htdocs\datawrapper\vendor\Slim\Slim.php(1145): Slim_Route->dispatch()
#10 C:\MAMP\htdocs\datawrapper\vendor\Slim\Middleware\Flash.php(84): Slim->call()
#11 C:\MAMP\htdocs\datawrapper\vendor\Slim\Middleware\MethodOverride.php(91): Slim_Middleware_Flash->call()
#12 C:\MAMP\htdocs\datawrapper\vendor\Slim\Middleware\PrettyExceptions.php(65): Slim_Middleware_MethodOverride->call()
#13 C:\MAMP\htdocs\datawrapper\vendor\Slim\Slim.php(1097): Slim_Middleware_PrettyExceptions->call()
#14 C:\MAMP\htdocs\datawrapper\www\index.php(94): Slim->run()
#15 {main}

**Comment by Marneus68** [comment]
I am getting the same issue on a fresh debian server.

Here's how it looks like for me:
![capture d ecran 2015-06-29 a 17 51 33](https://cloud.githubusercontent.com/assets/878305/8412048/9059b36c-1e87-11e5-9c93-15ceb34afd9e.png)

**Comment by arahayrabedian** [comment]
hey guys, make sure that your domains are set correctly, I had faced this issue previously, make sure that your 'charts' subdomain is configured and accessible from your datawrapper application server (do a lookup and curl)

that's what i had when i faced that issue at the time.

**Comment by Marneus68** [comment]
@arahayrabedian That might not be caused by the subdomains configuration. Like mentionned here https://github.com/datawrapper/datawrapper/issues/148 I only managed to fix it by copying dw-2.0.js to ./dw.js/dw-2.0.min.js and ./www/static/js/dw-2.0.min.js.
This is a problem

**Comment by arahayrabedian** [comment]
Haha I was about to reference dw2.0.js but thought it would be jumping to a
conclusion, good it fixed it for you

**Comment by gka** [comment]
you need to run `grunt` or `./node_modules/.bin/grunt` to build the JS libs/
