### ISSUE TITLE
Colorblind support

### ISSUE THREAD

**Issue by Putr** [datawrapper/datawrapper#163]
Hi, 
I'm a reader of a news site that users your system. The problem is that your line charts , as can be seen here:

http://www.delo.si/novice/politika/revizorji-prvic-na-sedezih-najvecjih-strank.html

are illegible to (partially) colorblind individuals (~5% of the population). We can't diffident between the colors all that well.

There are two standard solutions to this:
- add different pattern to each line (does not look good, bad with too many lines)
- (my recommended solution) add label to the value tooltip. Now it just lists the number, if it also listed the label, problem would be solved.

**Comment by gka** [comment]
the new line chart supports line patterns. otherwise, it's up to the chart creator to pick colors
