### ISSUE TITLE
"Get the data" link does not work in any recent of Internet Explorer

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#172]
**Error**: On IE 8/9/10 running on Windows 7/8/10, clicking a "get the data" link at the bottom of a chart e.g one from [this blog post](http://blogs.worldbank.org/opendata/future-world-s-population-4-charts) results in the following page being displayed.

![screen shot 2015-09-09 at 3 44 51 pm](https://cloud.githubusercontent.com/assets/192869/9772377/d0c856fa-5709-11e5-8c65-f914892b6276.png)

This seems to be caused by IE [not supporting Data URIs](https://stackoverflow.com/questions/17233034/data-uri-doesnt-work-with-ie) fully. 

**Expected behavior**: clicking the "Get the data" link in IE results in a CSV file of the data being downloaded or a new page with the data in tabular form being opened up.

**Comment by davidkokkelink** [comment]
This has been fixed for a while now :)
