### ISSUE TITLE
Update datawrapper

### ISSUE THREAD

**Issue by martgnz** [datawrapper/datawrapper#173]
Are the update instructions still similar to https://github.com/datawrapper/datawrapper/issues/61?

I saw some movement around bower/npm on the repo lately. How can we update datawrapper these days?

Thanks

**Comment by martgnz** [comment]
@gka do you have any hint?

**Comment by gka** [comment]
will look into the official [install guidelines](https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper) and try to bring them up to date..

**Comment by martgnz** [comment]
Thanks :+1:

**Comment by BrunoSalerno** [comment]
As @martgnz already asked, is there any advice on updating (from version 1.7.11 in my case)?
The instructions in #61 look quite outdated, and there is no info about it in the install guidelines.

cc @davidkokkelink 

Thanks in advance

**Comment by gka** [comment]
yes, the instructions are still up to date. the most important part are the DB schema updates. I added the `composer` commands which are also needed to run after the update
