### ISSUE TITLE
Custom tooltip plugin missing

### ISSUE THREAD

**Issue by martgnz** [datawrapper/datawrapper#174]
I've been trying to install the open source [map visualization plugin](https://bitbucket.org/jpp-cologne/plugin-visualization-maps/) but `custom-tooltip` is needed before.

Is it possible to open source it as well?

Thanks

**Comment by gka** [comment]
sorry, I forgot to open source it. here it is: https://bitbucket.org/jpp-cologne/plugin-custom-tooltip

**Comment by martgnz** [comment]
thanks! but after install it still goes undetected by `plugin-visualization-maps`
