### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by peterverweij** [datawrapper/datawrapper#176]
Hi all,
My name is Peter Verweij. I am working in datajournalism. Was trying to install datawrapper on my linux server. The install manual is rather limited. Got stuck with installing at the end:
after:
php scripts/plugin.php install "*".
I got:
PHP Parse error; syntax error; unexpected T-OBJECT_OPERATOR in /var/www/datawrapper.....twig-init.php on line 73.

Could you help me out?

Thank you

Peter

**Comment by Marneus68** [comment]
Hi,

What is the Linux distribution and version you're using?
Have you checked that your PHP version is equal to or greater than 5.2?

**Comment by peterverweij** [comment]
Hi Marneus68, I am running ubuntu linux 3.11.0.17  generic fir i386 with php 5.3.10. Will try to start again clean from scratch. I was not familair with curl and grunt but got the vendor software and could run grunt in the local directory without errors. then I followed the manual and ended with this parsing error

**Comment by monsdroid** [comment]
Same Error here. PHP 5.3.3

Goto twig-init.php
Replace line 73
```73
return (new \Moment\Moment($time))->fromNow()->getRelative();
```

with
```73
$dirtyFixMoment = new \Moment\Moment($time);
        return $dirtyFixMoment->fromNow()->getRelative();
```

Reason: Unfortunately, it is not possible to call a method on an object just created with new before PHP 5.4.

**Comment by peterverweij** [comment]
Hi Duane,

THanks for the update; noticed your contribution at Github.
I changed the code, but it did not solve the problem. After starting with a
complete fresh ubuntu, I was able to install datawrapper; working, except
publishing. I can print the graphs, but not save, although I have buttons
in my publish menu. The static directories are empty.
Cheers

Peter



On Wed, Jan 20, 2016 at 1:15 PM, monsdroid <notifications@github.com> wrote:

> Same Error here. PHP 5.3.3
>
> Goto twig-init.php
> Replace line 73
>
> return (new \Moment\Moment($time))->fromNow()->getRelative();
>
> with
>
> $dirtyFixMoment = new \Moment\Moment($time);
>         return $dirtyFixMoment->fromNow()->getRelative();
>
> Reason: Unfortunately, it is not possible to call a method on an object
> just created with new before PHP 5.4.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datawrapper/datawrapper/issues/176#issuecomment-173186239>
> .
>



-- 


*                   @ @------------oOO-(_)-OOo---------*

*Drs. Peter Verweij *    * D3-MEDIA*
peter@d3-media.nl
*Web*:   www.d3-media.nl
*Blogs*: d3-media.blogspot.com
           d3media.wordpress.com

**Comment by monsdroid** [comment]
HI Peter, 
a journey of our datawrapper installation adventure is here: Issue https://github.com/datawrapper/datawrapper/issues/184
Maybe you will find some solution. I added one for the missing Publish Button.

**Comment by peterverweij** [comment]
Hi Duane,

Thanks for this datawrapper update! Pity, I have to say that it did not
bring the solution for publishing the data. I had installed the Fernando
Rubens plugin; I can print a map; It give me a url of a graph, but the
graph is not saved at datawrapper static; folders are empty. Therefore
downloading results in an empty zip file.
Thanks for your effort and help.

Cu
Peter

On Mon, Jan 25, 2016 at 2:10 PM, monsdroid <notifications@github.com> wrote:

> HI Peter,
> a journey of our datawrapper installation adventure is here: Issue #184
> <https://github.com/datawrapper/datawrapper/issues/184>
> Maybe you will find some solution. I added one for the missing Publish
> Button.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datawrapper/datawrapper/issues/176#issuecomment-174504440>
> .
>



-- 


*                   @ @------------oOO-(_)-OOo---------*

*Drs. Peter Verweij *    * D3-MEDIA*
peter@d3-media.nl
*Web*:   www.d3-media.nl
*Blogs*: d3-media.blogspot.com
           d3media.wordpress.com

**Comment by gka** [comment]
I'm sorry but we can't provide support for installing Datawrapper, other than this document
https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper

if you get Datawrapper to work on your system, please update (add it to) our [installation guide](https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper) to share with other users.
