### ISSUE TITLE
Title text wrapping doesn't take position of social sharing icons into account

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#180]
For example: 

![image](https://cloud.githubusercontent.com/assets/192869/12273833/04de718e-b936-11e5-971d-cad3e224fa69.png)

**Comment by davidkokkelink** [comment]
fixed :) 

![bildschirmfoto 2016-01-12 um 20 20 05](https://cloud.githubusercontent.com/assets/6981408/12274176/eb2af832-b969-11e5-8718-0291c94713e8.png)

**Comment by tkb** [comment]
Awesome, thanks!
