### ISSUE TITLE
Large value bars cut off when range of values is big & labels in wrong position

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#182]
In [this case](https://datawrapper.dwcdn.net/wfaQn/1/), the range of values is 0.1 -> 52 and 0.97 -> 45.3 for two variables, the chart renders like this:

![image](https://cloud.githubusercontent.com/assets/192869/12296023/080988e2-b9d3-11e5-83d5-6114d106d65a.png)

And the bars are truncated with the labels for the largest value bars  in the wrong place (or perhaps the right place for a non-truncated bar?):

![image](https://cloud.githubusercontent.com/assets/192869/12296079/6feee826-b9d3-11e5-9991-2bbba83c4ae8.png)

or 

![image](https://cloud.githubusercontent.com/assets/192869/12296093/830ebe36-b9d3-11e5-80aa-dd762e5fe172.png)

Expected behavior is to have bars scaled to fit to iframe width, including labels at the same distance from each bar edge.

**Comment by davidkokkelink** [comment]
this issue was fixed with the launch of the new bar charts :)
