### ISSUE TITLE
Install Error - fightbulc/moment (1.0.0)

### ISSUE THREAD

**Issue by monsdroid** [datawrapper/datawrapper#183]
_Problem:_

```
....
- Installing fightbulc/moment (1.0.0)
    Downloading: 100%
    Extracting archive
    Invalid zip file, retrying...
```

Retrys until it fails

_Solution:_
-Edit composer.json
-Update fightbulc/moment Version to 1.14.1
-php composer.phar update
-php composer.phar install

_System:_
CentOS release 5.11 
PHP 5.3.3

**Comment by gka** [comment]
I'm sorry but we can't provide support for installing Datawrapper, other than this document
https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper

if you get Datawrapper to work on your system, please update (add it to) our [installation guide](https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper) to share with other users.
