### ISSUE TITLE
Install Errors Help (php 5.3.3) 

### ISSUE THREAD

**Issue by monsdroid** [datawrapper/datawrapper#184]
**_Journey to and from installing Datawrapper**_
Installing Datawrapper isnt always easy especally if your are running on php <= 5.3.3
Here are Problems we had so far and how we fixed them. I think quite a few are easy avoidable with small updates to the install scripts/documentation and packet manager settings.

**Problem 1:**

```
- Installing fightbulc/moment (1.0.0)
    Downloading: 100%
    Extracting archive
    Invalid zip file, retrying...
```

Solution 1:

```
-Edit composer.json
-Update fightbulc/moment Version to 1.14.1
php composer.phar update
php composer.phar install
```

**Problem 2:**

```
PHP Parse error; syntax error; unexpected T-OBJECT_OPERATOR in /var/www/datawra...twig-init.php on line 73.
```

Solution 2:

```
Goto lib/twig-init.php
Replace line 73
  return (new \Moment\Moment($time))->fromNow()->getRelative();
with
  $dirtyFixMoment = new \Moment\Moment($time);
        return $dirtyFixMoment->fromNow()->getRelative();
```

**Problem 3:**

```
The front Page looks funny (bootstrap.css etc. missing)
```

Solution 3:

```
make sure bower is installed, run bower and grunt again
  npm install -g bower
  bower install
  grunt
```

**Problem 4:**

```
Timeout in JShrink/Minifier.php
```

Solution 4:

```
You probably using php 5.3.3 with mbstring.func_overload = 2 
You got 3 choices. 
A: set func_overload to 0 (recommend that, mbstring functions are slow. really slow)
B: Edit Minifier.php to pass trough the files instead of compressing them
C. Edit Minifier.php getChar function to use something like this http://stackoverflow.com/a/14366023/1393681
```

**Problem 5:**

```
No Publish Button
```

Solution 5:
Source: https://github.com/datawrapper/datawrapper/issues/146

```
Install Plugin from https://github.com/rubensfernando/publish-embed
-- Download
-- Put in dw/plugins Folder
-- open shell in dw root 
-- php scripts/plugin.php install publish-embed
```

**Comment by felipe-couto** [comment]
thank you, I was able to almost get it running with CentOS 6

Now I have this error:

[Wed Feb 03 16:49:24 2016] [error] [client 172.17.35.188] PHP Parse error:  syntax error, unexpected T_STRING, expecting T_VARIABLE or '$' in /opt/datawrapper/lib/utils/twig-init.php on line 69

**Comment by gka** [comment]
I'm sorry but we can't provide support for installing Datawrapper, other than this document
https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper

if you get Datawrapper to work on your system, please update (add it to) our [installation guide](https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper) to share with other users.
