### ISSUE TITLE
Social media icons interfering with split bar charts

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#186]
![image](https://cloud.githubusercontent.com/assets/192869/12458038/aaf4815e-bf75-11e5-85c8-0e3995c20b79.png)

in 

https://datawrapper.dwcdn.net/qsUsR/3/

**Comment by tkb** [comment]
Hi, not sure if this has been looked at yet, it also presents i[tself like this](https://datawrapper.dwcdn.net/42qjd/5/):

![image](https://cloud.githubusercontent.com/assets/192869/13078065/cbbc9cbc-d48a-11e5-85b0-c2f6b1fe9b75.png)

In this case it would be good to have some more padding around the social sharing icons / have a larger  minimum distance between the social share buttons and the chart elements.

**Comment by tkb** [comment]
Hi, just a variation on the theme, the split bar charts are great for including narratives in the text itself but if the line of text goes too long, it's also obscured by the social media buttons: 

![image](https://cloud.githubusercontent.com/assets/192869/13188284/8c5500dc-d71e-11e5-8b7c-f155001481df.png)

**Comment by davidkokkelink** [comment]
Thanks so much for the detailed reporting. We've deployed a fix that corrects the spacing between the sharing button and the chart itself, the headline and description, and group labels if necessary. The mentioned charts now look like this:

![bildschirmfoto 2016-02-22 um 12 33 08](https://cloud.githubusercontent.com/assets/6981408/13217146/b3011286-d960-11e5-9986-8e5971f95dd7.png)

![bildschirmfoto 2016-02-22 um 12 33 23](https://cloud.githubusercontent.com/assets/6981408/13217150/b6a55578-d960-11e5-958e-ff535b6c472d.png)

![bildschirmfoto 2016-02-22 um 12 34 01](https://cloud.githubusercontent.com/assets/6981408/13217154/b9e3382c-d960-11e5-889b-21eed4597a32.png)
