### ISSUE TITLE
Feature request: add text to social sharing message (particularly Twitter) 

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#187]
Right now, when sharing a chart with the twitter icon inside a chart results in a message that contains only the URL:
## Clicking on tweet link inside chart

![image](https://cloud.githubusercontent.com/assets/192869/12848655/3dc86eda-cbe9-11e5-86db-1881b331f7a1.png)

By contrast, most social sharing functions either automatically include or allow an editor to include a message as well as a URL. The [same page as above ](http://blogs.worldbank.org/opendata/chart-2030-delhi-s-population-will-approach-tokyo-s) includes a Tweet button and this is the message that gets created instead:
## Clicking on tweet link on the blog page

![image](https://cloud.githubusercontent.com/assets/192869/12848706/78f0987a-cbe9-11e5-9a2e-7562f77cfdf7.png)

This kind of message not only tends to generate more clicks, but having the ability to control the content of the message is generally more useful in creating a post that's easier to understand and offers context. 

One possible solution would be to have the "manually enter URL" field just be "manually enter message" and let it be free-text that can include a URL and any other text as needed. 

Thanks!

**Comment by gka** [comment]
this is a good idea. will add it to our internal ticket system. thanks
