### ISSUE TITLE
Install Error 

### ISSUE THREAD

**Issue by CHesseling** [datawrapper/datawrapper#191]
Hi,
after going through all [these steps](https://github.com/datawrapper/datawrapper/wiki/Installing-Datawrapper) including [Problem 2](https://github.com/datawrapper/datawrapper/issues/184) I got this one:

Parse error: syntax error, unexpected '[' in /www/htdocs/my_user_name/datawrapper/controller/chart/visualize.php on line 17

Any ideas?

**Comment by simardcasanova** [comment]
Hi Claus,

Did you manage to make it work? I have the very same issue, and no clue about how to solve it…

Thanks!

**Comment by gka** [comment]
I'm sorry but we can't provide support for installing Datawrapper, other than this document
https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper

if you get Datawrapper to work on your system, please update (add it to) our [installation guide](https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper) to share with other users.
