### ISSUE TITLE
Bug: Line chart legend element in wrong position when data missing from series

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#192]
Hi, in this chart: datawrapper.dwcdn.net/saG45/1/ I have no data for the last 2 points in the "Middle East" series and as a result, the legend item for Middle East is in an unexpected position:

![image](https://cloud.githubusercontent.com/assets/192869/14530172/b9a74af4-0225-11e6-9398-3f78652390e8.png)

Suspect this is happening because the legend element is positioned relative to the max x-value of the series.

Thanks

**Comment by davidkokkelink** [comment]
Thanks for the report, issue is fixed. You may need to empty your browser cache to get the new version immediately. Also, the chart will need to be re-published for the changes to take effect in the live version :)

![bildschirmfoto 2016-04-14 um 16 26 14](https://cloud.githubusercontent.com/assets/6981408/14531464/b920ee22-025d-11e6-9f0f-8139c98baea1.png)
