### ISSUE TITLE
Bug: Social sharing buttons not appearing on new datawrapper maps

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#193]
For example, on this map: https://datawrapper.dwcdn.net/wpuPm/2/  when I select the social sharing icons checkbox, they don't appear:

![image](https://cloud.githubusercontent.com/assets/192869/14589271/08cc8dfa-04ac-11e6-8fdd-ab4a12e3a62d.png)

**Comment by davidkokkelink** [comment]
Issue is fixed now. This issue wasn't caught in testing as it only appeared when having social sharing _enabled_ and map legends _disabled_, so thanks a lot for reporting this!

![bildschirmfoto 2016-04-18 um 15 04 41](https://cloud.githubusercontent.com/assets/6981408/14605030/eb54bd80-0576-11e6-92d9-3583caa3a994.png)

**Comment by tkb** [comment]
Great, thanks. 

Goddam edge cases!
