### ISSUE TITLE
404 on "GET /api/auth/salt HTTP/1.1"

### ISSUE THREAD

**Issue by mapausch** [datawrapper/datawrapper#198]
Hello,

I'm on Oracle Linux 7.2 x86_64 and struggling around  to get datawrapper running.

I followed the steps in https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper
Additionally I had to create dw-2.0.min.js and queue.min.js manually (like described in other issues).

When I try to create a new account, than nothing happens when I click the "Sign Up " button in the "Create a new account" form.

I had a look on the apache error_log and access_log and there I can see the following line
when I click "Login / Sign Up" on the start page:
10.x.x.x - - [13/May/2016:11:22:33 +0200] _**"GET /api/auth/salt HTTP/1.1" 404**_ 211 "http://my.datawrapper.local/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"

**Comment by greglinch** [comment]
I have the same issue. I'm running Ubuntu 14 on AWS.

**Comment by rubensfernando** [comment]
I've had the same issue. if I'm not mistaken, you need add "auth_salt" and "secure_auth_key" in config.yaml.

**Comment by greglinch** [comment]
@rubensfernando Thanks! I've had both of those in my `config.yaml` the whole time, but still get that error. Is this the correct formatting (with quotes around both)?

auth_salt: "<auth_salt>"
secure_auth_key: "<secure_auth_key>"

**Comment by mapausch** [comment]
I also added auth_salt and secure_auth_key because I think I read it in another issue. But also still had the error.

**Comment by greglinch** [comment]
In the console, besides the initial `jquery.js:9666 GET http://mccdata-test.mcclatchydc.com/api/auth/salt 404 (Not Found)`, when hit "sign up" the error is `hmac-sha256.js:16 Uncaught TypeError: Cannot read property 'sigBytes' of undefined`

Here's a previous thread on this, which was marked as resolved last year:

https://github.com/datawrapper/datawrapper/issues/107

Given that at least two of us have had this issue, it'd be great if someone could look into this again or provide instructions on how to fix on our end.

**Comment by rubensfernando** [comment]
I running new application of DW using Ubuntu 14 on Vagrant. The same erro happened. I edited config file of Apache2  (httpd-app.conf, in my case) and I changed  `AllowOverride None` to  `AllowOverride All`. And works fine.

**Comment by greglinch** [comment]
Thanks, @rubensfernando. I've tried that on the root and www directories. When I update root, I get a 500. When I update www, the same error persists. Here's my config: 
```
<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
```
Any other advice? Thanks again!

**Comment by mapausch** [comment]
@rubensfernando 
AllowOverride didn't work for me either.
I tried to set it in /api/.htaccess

In general for me it seems like there are some files and/or directories are missing in /api directory.
I only have .htaccess and index.php there.
But according to Apaches access_log there should also be a directory "auth" containing a file "salt".

In www directory I found api-test.html. Called this from my browser. And when I try to "test" the api there are 404s on any action I try from api-test.html

In directory $DocumentRoot/datawrapper/lib/api I found php files that _could_ be the files that are (maybe) missing in api directory and are referenced from api-test.html. So maybe there's some kind of "missing link" between this 2 directories?

**Comment by deshetti** [comment]
@greglinch Not sure if you were able to resolve the issue. Performing the two steps @rubensfernando mentioned worked for me:

1. add "auth_salt" and "secure_auth_key" in config.yaml. @greglinch please get the auth_salt and secure_auth_key from here: http://api.wordpress.org/secret-key/1.1/salt/
I also ran the following command after making the change: php secure_passwords.php
The above step is mentioned here: https://github.com/datawrapper/datawrapper/wiki/Enabling-secure-auth-key
2. I updated AllowOverride All:
	<Directory "/var/www">
	<Directory "/var/www/html">
        <Directory "/var/www/cgi-bin">

Hopefully this helps.

**Comment by mapausch** [comment]
@deshetti 
Thanks a lot. This worked for me.
No 404 anymore. And Sign Up now works.

**Comment by greglinch** [comment]
@deshetti Ah, I didn't know about this step:

https://github.com/datawrapper/datawrapper/wiki/Enabling-secure-auth-key

I did that and added those directories with `AllowOverride All` to my Apache config, but I still get the same console error after restarting Apache and reloading the page:

`jquery.js:9666 GET http://mccdata-test.mcclatchydc.com/api/auth/salt 404 (Not Found)`

And then this when I click "sign up" after entering a new username and password:

`hmac-sha256.js:16 Uncaught TypeError: Cannot read property 'sigBytes' of undefined`

Any other advice? Thanks very much!

**Comment by deshetti** [comment]
@greglinch 

Can you do edit the following files and see if that helped:

datawrapper/www/api/.htaccess
`RewriteBase /api`
datawrapper/www/.htaccess
` RewriteBase /`

**Comment by greglinch** [comment]
@deshetti Thanks. Just added those and the same issues persist.

**Comment by deshetti** [comment]
@greglinch Did you restart apache after the changes?

**Comment by greglinch** [comment]
@deshetti Yup! Always :)
