### ISSUE TITLE
Charts not publishing after completing steps

### ISSUE THREAD

**Issue by greglinch** [datawrapper/datawrapper#204]
My setup:

- EC2 server running Ubuntu 14
- Datawrapper 1.10.3
- PHP 5.5.9

I've set up Datawrapper and installed various additional plugins from the [Bitbucket repo](https://bitbucket.org/jpp-cologne/). All of the upload/check/visualize/publish steps work, including the preview, until I get the embed and test the source file for existing charts, which doesn't exist. I've tried playing with various `config.yaml` settings (e.g. setting the chart path manually and removing). 

Here are three main symptoms of charts failing to publish, in case any offer hints:

- the index file 404s when checking on charts subdomain, which I've confirmed works generally because `m.png` appears there on a `charts.domain.com` URL
- trying to download the archive results in this error because the index and other files don't exist
<img width="1056" alt="screen shot 2016-06-28 at 2 32 14 pm" src="https://cloud.githubusercontent.com/assets/327783/16499286/a8c2e77c-3ecd-11e6-87c4-dfebe6406352.png">
- S3 publishing also doesn't work because there's no original files to copy there (assuming that's how it works, although I know there could be different issues at play)

Any suggestions?

**Comment by greglinch** [comment]
Here's an example of my final screen

![screen shot 2016-06-30 at 2 36 59 pm](https://cloud.githubusercontent.com/assets/327783/16499881/2aa26054-3ed0-11e6-8656-bc4b0a6eb2b0.png)

And a list of the plugins I've installed:

```
admin-jobs
admin-themes
admin-users
color-category-selector
color-gradient-selector
core-demo-datasets
core-vis-options
custom-tooltip
email-native
export-image
export-print-pdf
export-static-png
export-zip
gallery
phantomjs
publish-s3
snapshot
theme-autumn
theme-default
theme-slate
visualization
visualization-bar-chart
visualization-column-charts
visualization-data-table
visualization-election-donut
visualization-line-chart
visualization-maps
visualization-pie-chart
visualization-raphael-chart
```

**Comment by greglinch** [comment]
I found an error earlier in the process, which turns out to have been the cause of index and other files not being generated. 

Here's what was happening:

One the visualization step, I saw a console error for a 404 on `domain.com/vendor/innersvg/innersvg.js`. The file actually exists, so I made sure it had the correct owner/permissions and then added the following rewrite rule to `~/datawrapper/www/.htaccess`:

```
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^vendor/(.*)$ /static/vendor/$1 [R=301,L]
```

Then I went back through and published my charts and they worked as expected. The only issue I'm current experiencing involves the charts not publishing to S3.

**Comment by lorenries** [comment]
@greglinch were you able to publish to S3? I've been banging my head against the wall because attempting to publish to S3 is causing a 500 internal server error.

BTW I'm using your setup instructions on EC2.

Any suggestions would be greatly appreciated!

**Comment by greglinch** [comment]
@lorenries Sorry for the delay. Yes, I'm able to publish to S3. Try including `endpoint` in your `config.yaml` file with a value that matches your bucket. For example:

`endpoint: s3-us-east-1.amazonaws.com`

More info here: https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

Let me know if that helps!

**Comment by lorenries** [comment]
@greglinch Thanks! Unfortunately it still isn't working. I reinstalled from scratch on EC2 and followed your instructions to the t, but I'm still getting this:

![screen shot 2016-09-01 at 3 04 24 pm](https://cloud.githubusercontent.com/assets/17712866/18180634/c68dc5b0-7055-11e6-95fe-ec17833a742b.png)

**Comment by greglinch** [comment]
@lorenries Hmm. I don't think I've seen that one before. I'll have to get back to you with possible fixes.
