### ISSUE TITLE
Missing invitation_link in "You've been invited to Datawrapper!" email

### ISSUE THREAD

**Issue by greglinch** [datawrapper/datawrapper#205]
I've added a new user to a self-hosted installation of Datawrapper, but the user received an email with a missing invitation link, like this:

> To activate the account and choose a password please click on the following link: 
> %invitation_link%

All of the other values (e.g. their email, the domain, my email address) passed through to the template successfully, but not this one. I've replicated on my test and prod environments.

Also, I've confirmed the activate_token exists by checking the `user` table in the database.

Here's are some relevant files:
- email script: https://github.com/datawrapper/datawrapper/blob/126135eaff2f1d465129fe882ed754db135ebc8c/plugins/email-native/init.php
- email template: https://raw.githubusercontent.com/datawrapper/datawrapper/126135eaff2f1d465129fe882ed754db135ebc8c/plugins/email-native/locale/en_US.json

Any thoughts or advice for fixing this issue?

**Comment by lorenries** [comment]
Not sure if you've tried this, but this pull request seemed to work: https://github.com/datawrapper/datawrapper/pull/196

**Comment by greglinch** [comment]
@lorenries Whoa, somehow missed that. I'll give it a try. Thanks very much!

**Comment by davidkokkelink** [comment]
was fixed in pull request
