### ISSUE TITLE
Offering updated, step-by-step installation instructions

### ISSUE THREAD

**Issue by greglinch** [datawrapper/datawrapper#206]
Offering this for the main wiki:

https://gist.github.com/greglinch/dd964d56db5e3522d1fad17fd72d4251#file-datawrapper-install-instructions-detailed-md

**Comment by rubensfernando** [comment]
Excellent work @greglinch!

**Comment by greglinch** [comment]
Thanks, @rubensfernando!

**Comment by gka** [comment]
thanks, adding to the wiki

**Comment by gka** [comment]
btw, our wiki is now writable to everyone.
