### ISSUE TITLE
Bug: social sharing buttons not displaying on embedded version of line chart

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#210]
On this new line chart, social sharing buttons are enabled: https://datawrapper.dwcdn.net/KhKZK/4/

But they do not appear when the chart is embedded:
http://blogs.worldbank.org/opendata/chart-worlds-top-tourist-destinations

**Comment by davidkokkelink** [comment]
Thanks for reporting, is fixed now!
