### ISSUE TITLE
Bug: x-axis labels incorrect on new line chart

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#212]
On this chart: https://datawrapper.dwcdn.net/Vmqiy/1/ at smaller sizes, the x-axis ticks are in the wrong position but they appear correct when the chart is in full screen: 

![image](https://cloud.githubusercontent.com/assets/192869/19351721/d98cdcc8-912a-11e6-8d90-ebbc543b662c.png)

**Comment by tkb** [comment]
Just wanted to flag this one again, here's another example: 
![image](https://cloud.githubusercontent.com/assets/192869/21031331/d6efbf90-bd70-11e6-848f-026e4aba4953.png)
https://datawrapper.dwcdn.net/dbQVW/1/

**Comment by tkb** [comment]
And in case it's useful, I see the bug with these two charts on Mac versions of:

Chrome: 55.0.2883.75
Firefox: 50.0.2
Safari: 10.0.1

And in all 3 cases, the axis displays correctly in full-screen but if I resize to something the size of a normal embed, bugs like the above appear.

**Comment by gka** [comment]
sorry @tkb.

this is fixed now. try republishing the chart and let me know if you see it happen again.

**Comment by tkb** [comment]
@gka - working as expected now, thanks!
