### ISSUE TITLE
Bug? "Created with Datawrapper" displaying on bottom of chart

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#220]
We're on a custom plan and it looks like on the latest update to Datawrapper, with any of the layouts, "Created with Datawrapper" appears at the bottom of the chart.  Expected behavior is for there just to be the source text/link there. 

![image](https://user-images.githubusercontent.com/192869/28029911-a3ef8858-656f-11e7-9eaf-788ca79421e2.png)

**Comment by davidkokkelink** [comment]
hi tariq, thanks for reporting. is fixed, details follow in e-mail :)
