### ISSUE TITLE
new to Datawrapper

### ISSUE THREAD

**Issue by alshaikh1** [datawrapper/datawrapper#223]
Hi,

I have followed the installation manual and installed Datawrapper successfully. I have got the welcome page and asking to create a template.

Does Datawrapper have the pages similar to datawrapper.de ? The purpose is to enable users to create and customize their charts.

**Comment by FraTheVet** [comment]
Can't really tell what the issue is on this case, could you be more specific?

**Comment by alshaikh1** [comment]
Sure, 
I want to make a website like datawrapper.de
but when I launched datawrapper, all I've got is a Welcome page.
