### ISSUE TITLE
Maps tooltip

### ISSUE THREAD

**Issue by DivyanshiWadhwa** [datawrapper/datawrapper#231]
I'm using the tooltop for the map. Above the title, there is an "x" for some reason. Below is a screenshot and link: https://app.datawrapper.de/map/VHIjC/publish

Is there a way to remove this x from the tooltip title?
![image](https://user-images.githubusercontent.com/36739437/44223790-9f7f9c80-a156-11e8-907f-cd58ef0d6ff5.png)

**Comment by ilokhov** [comment]
Hi, looking at the map now, it appears that the "x" is not present in the tooltip. If you are still seeing it, please let us know what browser/OS you are using in a comment.

**Comment by DivyanshiWadhwa** [comment]
I do still see it. I'm using Google Chrome on a Windows Thinkpad.

**Comment by ilokhov** [comment]
Am I correct in assuming that you're using a tablet? The "x" button should be present on all touch devices to enable closing the tooltip. The button does not appear when I test it on a desktop Windows device with Google Chrome.

**Comment by ilokhov** [comment]
Thanks for the suggestions - I will include them in our list of potential updates.
